# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes@4.27.2"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
rtl                      : # true, false (default) # turns direction of the page into right to left for RTL languages
title                    : "Sleeping Kingz"
title_separator          : "-"
subtitle                 : "Where Royalty Rests, Rappers Rise."
name                     : "Sleeping Kingz LLC"
description              : "An independent music label pushing the boundaries with artists like XiØN and OhHeyItsJae."
url                      : "https://sleeping-kingz.github.io"
baseurl                  : ""
repository               : "Sleeping-Kingz/sleeping-kingz.github.io"
teaser                   : "/assets/images/teaser.png"
logo                     : "/assets/images/logo.png"
masthead_title           : "Sleeping Kingz"
breadcrumbs              : true
words_per_minute         : 200
enable_copy_code_button  : false
copyright                : "Sleeping Kingz LLC"
copyright_url            : "https://sleeping-kingz.github.io"

comments:
  provider               : false
  disqus:
    shortname            : 
  discourse:
    server               : 
  facebook:
    appid                : 
    num_posts            : 5
    colorscheme          : "dark"
  utterances:
    theme                : "github-dark"
    issue_term           : "pathname"
  giscus:
    repo_id              : 
    category_name        : 
    category_id          : 
    discussion_term      : "pathname"
    reactions_enabled    : '1'
    theme                : "dark"
    strict               : 0
    input_position       : "bottom"
    emit_metadata        : 0
    lang                 : "en"
    lazy                 : false
  staticman:
    branch               : "master"
    endpoint             : 

reCaptcha:
  siteKey                :
  secret                 :

atom_feed:
  path                   : 
  hide                   : false

search                   : true
search_full_content      : false
search_provider          : lunr
lunr:
  search_within_pages    : false

algolia:
  application_id         : 
  index_name             : 
  search_only_api_key    : 
  powered_by             : true

google:
  search_engine_id       : 
  instant_search         : false

# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : "XiONDiGiTaL"
facebook:
  username               : ""
  app_id                 : ""
  publisher              : ""
og_image                 : "/assets/images/og-image.png"
social:
  type                   : "Person"
  name                   : "XiØN"
  links:
    - label: "Linktree"
      icon: "fas fa-fw fa-link"
      url: "https://linktr.ee/xiondigital"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/XiONDiGiTaL"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/xiondigital2"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Sleeping-Kingz"

# Analytics
analytics:
  provider               : false
  google:
    tracking_id          : 
    anonymize_ip         : false

# Site Author
author:
  name             : "Sleeping Kingz LLC"
  avatar           : "/assets/images/label-avatar.png"
  bio              : "A forward-thinking label dedicated to pushing the limits of music through visionary artists."
  location         : "Global"
  email            : ""
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:contact@sleepingkingz.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://sleeping-kingz.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/XiONDiGiTaL"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: ""
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Sleeping-Kingz"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/xiondigital2"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/XiONDiGiTaL"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: ""
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Sleeping-Kingz"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: ""
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: ""
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/xiondigital2"
  since: "2010"

# Reading Files
include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: 

# Pagination with jekyll-paginate
paginate: 5
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
pagination:
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
